name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: run test
        run: npm run test
        
  testE2E:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: install playwright
        run: npx playwright install --with-deps
      - name: Run playwright tests
        run: npm run test:e2e

      
name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.helgituan }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.aRWcKZlUbECPJdrcvTHo7udu }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.aRWcKZlUbECPJdrcvTHo7udu }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.aRWcKZlUbECPJdrcvTHo7udu }}